name: Update stocks.json every minute
on:
  schedule:
    - cron:  '*/1 * * * *'     # كل دقيقة
  workflow_dispatch:            # تشغّله يدوي لو حبيت
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: pip install requests

      - name: Run update script
        run: python update_feed.py

      - name: Commit & push
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "GitHub Actions Bot"
          git add stocks.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "auto: update $(date -u +'%H:%M:%S')"
            git push
          fi
